-- HQ_README_INTRO

INSERT INTO HQ_SCORE_INTRO (TYPE, LOW, HIGH, KEY) VALUES ('diet', 90, 2147483647, 'diet-90-99');
INSERT INTO HQ_SCORE_INTRO (TYPE, LOW, HIGH, KEY) VALUES ('diet', 70, 89, 'diet-70-89');
INSERT INTO HQ_SCORE_INTRO (TYPE, LOW, HIGH, KEY) VALUES ('diet', 50, 69, 'diet-50-69');
INSERT INTO HQ_SCORE_INTRO (TYPE, LOW, HIGH, KEY) VALUES ('diet', 0, 49, 'diet-13-49');
INSERT INTO HQ_SCORE_INTRO (TYPE, LOW, HIGH, KEY) VALUES ('lifestyle', 90, 2147483647, 'lifestyle-90-99');
INSERT INTO HQ_SCORE_INTRO (TYPE, LOW, HIGH, KEY) VALUES ('lifestyle', 70, 89, 'lifestyle-70-89');
INSERT INTO HQ_SCORE_INTRO (TYPE, LOW, HIGH, KEY) VALUES ('lifestyle', 50, 69, 'lifestyle-50-69');
INSERT INTO HQ_SCORE_INTRO (TYPE, LOW, HIGH, KEY) VALUES ('lifestyle', 0, 49, 'lifestyle-13-49');

-- HQ_SCORE_QUESTIONS

INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('lifestyle', 'energy');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('lifestyle', 'stress');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('lifestyle', 'sleep');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('lifestyle', 'memory');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('lifestyle', 'exercise_frequency');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('lifestyle', 'exercise_intensity');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('diet', 'fruits');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('diet', 'vegetables');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('diet', 'grains');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('diet', 'dairy');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('diet', 'healthy_fats');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('diet', 'sugar_drinks');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('diet', 'junk_food');
INSERT INTO HQ_SCORE_QUESTIONS (TYPE, QUESTION_TYPE) VALUES ('diet', 'breakfast');


-- HQ_SCORE_ANSWERS

-- lifestyle
-- energy
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (1, 0, 35, 1, 'bullet-key-1');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (1, 1, 60, 9, 'bullet-key-2');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (1, 2, 80, 12, 'bullet-key-3');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (1, 3, 95, 17, 'bullet-key-4');
-- stress
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (2, 0, 95, 20, 'bullet-key-5');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (2, 1, 80, 13, 'bullet-key-6');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (2, 2, 60, 6, 'bullet-key-7');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (2, 3, 35, 3, 'bullet-key-8');
-- sleep
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (3, 0, 50, 5, 'bullet-key-9');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (3, 1, 80, 7, 'bullet-key-10');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (3, 2, 75, 11, 'bullet-key-11');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (3, 3, 95, 18, 'bullet-key-12');
-- memory
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (4, 0, 50, 2, 'bullet-key-16');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (4, 1, 80, 10, 'bullet-key-15');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (4, 2, 95, 15, 'bullet-key-14');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (4, 3, 95, 16, 'bullet-key-13');
-- frequency
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (5, 0, 30, 4, 'bullet-key-17');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (5, 1, 40, 8, 'bullet-key-18');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (5, 2, 80, 14, 'bullet-key-19');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (5, 3, 95, 19, 'bullet-key-20');
-- intensity
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (6, 0, 60, 1000, 'bullet-key-21');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (6, 1, 80, 1000, 'bullet-key-22');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (6, 2, 95, 1000, 'bullet-key-23');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (6, 3, 95, 1000, 'bullet-key-24');

-- diet
-- fruit
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (7, 0, 30, 9, 'bullet-key-25');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (7, 1, 75, 17, 'bullet-key-26');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (7, 2, 95, 26, 'bullet-key-27');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (7, 3, 95, 27, 'bullet-key-28');
-- vegetables
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (8, 0, 25, 3, 'bullet-key-29');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (8, 1, 50, 12, 'bullet-key-30');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (8, 2, 85, 18, 'bullet-key-31');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (8, 3, 95, 32, 'bullet-key-32');
-- grains
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (9, 0, 25, 10, 'bullet-key-33');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (9, 1, 50, 15, 'bullet-key-34');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (9, 2, 85, 20, 'bullet-key-35');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (9, 3, 95, 31, 'bullet-key-36');
-- dairy
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (10, 0, 25, 11, 'bullet-key-37');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (10, 1, 50, 19, 'bullet-key-38');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (10, 2, 85, 24, 'bullet-key-39');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (10, 3, 95, 25, 'bullet-key-40');
-- healthy fats
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (11, 0, 20, 5, 'bullet-key-41');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (11, 1, 30, 6, 'bullet-key-42');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (11, 2, 64, 23, 'bullet-key-43');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (11, 3, 95, 33, 'bullet-key-44');
-- water
--INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK) VALUES (12, 0, 0, 1000, 'bullet-key-45');
--INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK) VALUES (12, 1, 0, 1000, 'bullet-key-46');
--INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK) VALUES (12, 2, 0, 1000, 'bullet-key-47');
--INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK) VALUES (12, 3, 0, 1000, 'bullet-key-48');
-- sugar drink
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (12, 0, 95, 29, 'bullet-key-49');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (12, 1, 70, 14, 'bullet-key-50');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (12, 2, 40, 8, 'bullet-key-51');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (12, 3, 25, 2, 'bullet-key-52');
-- junk food
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (13, 0, 95, 30, 'bullet-key-53');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (13, 1, 70, 13, 'bullet-key-54');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (13, 2, 40, 4, 'bullet-key-55');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (13, 3, 25, 1, 'bullet-key-56');
-- breakfast
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (14, 0, 25, 16, 'bullet-key-57');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (14, 1, 70, 22, 'bullet-key-58');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (14, 2, 25, 7, 'bullet-key-59');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (14, 3, 85, 21, 'bullet-key-60');
INSERT INTO HQ_SCORE_ANSWERS (QID, ANSWER, SCORE, RANK, KEY) VALUES (14, 4, 95, 25, 'bullet-key-61');