use ICSHKTST;

DROP TABLE
    HQ_USER_DATA_STORAGE;
    
    
CREATE TABLE
    HQ_USER_DATA_STORAGE
    (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        ACCOUNT_ID CHARACTER(7),
        CONTACT_ID CHARACTER(9),
        EMAIL VARCHAR(128),
        FIRST_NAME VARCHAR(100),
        LAST_NAME VARCHAR(100),
        HEALTH_PROFILE_ID VARCHAR(50) NOT NULL,
        ANSWERS_JSON TEXT,
        OPT_IN SMALLINT,
        UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        HOST_NAME VARCHAR(255),
        REFERRER_CODE VARCHAR(30),
        SHARE_WITH_DISTRIBUTORS SMALLINT DEFAULT 1,
        PRIMARY KEY (HEALTH_PROFILE_ID),
        UNIQUE (ID)
    );

 -- Get data where userId is not null
 
 SELECT
    HQ.USER_ID AS ACCOUNT_ID,
    CONCAT(HQ.USER_ID, '-1') AS CONTACT_ID,
    U.EMAIL         AS EMAIL,
    COALESCE(NULLIF(HQ.FIRST_NAME,''), U.P1_FIRST_NAME),
    COALESCE(NULLIF(HQ.LAST_NAME,''), U.P1_LAST_NAME ),
    HQ.HEALTH_PROFILE_ID,
    HQ.ANSWERS_JSON,
    HQ.OPT_IN,
    HQ.UPDATED,
    HQ.CREATED,
    HQ.HOST_NAME,
    HQ.REFERRER_CODE,
    HQ.SHARE_WITH_DISTRIBUTORS
FROM
    HQ_USER_DATA_STORAGE HQ
LEFT JOIN
    ext_user U
ON
    HQ.USER_ID = U.USER_LOGIN_ID
WHERE
    HQ.USER_ID IS NOT NULL;
