CREATE TABLE
    PROMO_USER_GROUP
    (
        GROUP_ID INTEGER NOT NULL,
        SHAKLEE_ID CHARACTER(7) NOT NULL,
        EXTRA_1 VARCHAR(1024),
        EXPIRATION TIMESTAMP,
        PRIMARY KEY (SHAKLEE_ID, GROUP_ID)
    );