drop table PROMO_ARBITRATOR;

CREATE TABLE
    PROMO_ARBITRATOR
    (
        ID INTEGER  NOT NULL AUTO_INCREMENT,
        IMPLEMENTING_CLASS VARCHAR(128) NOT NULL,
        JSON_SERIALIZED VARCHAR(4048) NOT NULL,
        COUNTRY_CODE CHARACTER(2) NOT NULL,
        TYPE VARCHAR(10) NOT NULL,
        RULESET_GROUP VARCHAR(10) NOT NULL,
        PRIMARY KEY(ID)
    );