DROP TABLE HQ_REPORT;

CREATE TABLE
    HQ_REPORT
    (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        REFERRER_ID CHARACTER(20) NOT NULL,
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        HQ_ID BIGINT NOT NULL,
        DIRECT_REFERRAL SMALLINT,
        PRIMARY KEY (ID),
        CONSTRAINT FK1_HQ_ID FOREIGN KEY (HQ_ID) REFERENCES HQ_USER_DATA_STORAGE (ID) ON
    DELETE
        CASCADE
    );