CREATE TABLE
    PROMO
    (
        ID INTEGER NOT NULL AUTO_INCREMENT,
        NAME VARCHAR(50) NOT NULL,
        CODE VARCHAR(50) NOT NULL,
        DESCRIPTION VARCHAR(200),
        PRIORITY INTEGER NOT NULL,
        START_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        END_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        ACTIVE SMALLINT NOT NULL,
        COUNTRY_CODE CHARACTER(2) NOT NULL,
        GROUP_ID INTEGER,
        RULESET_GROUP VARCHAR(10) NOT NULL,
        PRIMARY KEY (ID)
    );