drop table PROMO_COMPONENT_PARAM;

CREATE TABLE
    PROMO_COMPONENT_PARAM
    (
        ID INTEGER  NOT NULL AUTO_INCREMENT,
        PROMO_COMPONENT_ID INTEGER NOT NULL,
        NAME VARCHAR(50) NOT NULL,
        VAL VARCHAR(1028) NOT NULL,
        PRIMARY KEY (ID),
        CONSTRAINT PROMO_PARAM_PROMO_COMPONENT_FK FOREIGN KEY (PROMO_COMPONENT_ID) REFERENCES
        PROMO_COMPONENT (ID) ON
    DELETE
        CASCADE
    );