drop table PROMO_RULESET_SEQ;

create table PROMO_RULESET_SEQ
 (ID INTEGER NOT NULL AUTO_INCREMENT,
          PROMO_ID INTEGER NOT NULL,
          PRIMARY KEY (ID),
        CONSTRAINT PROMO_RULESET_SEQ_PROMO_FK FOREIGN KEY (PROMO_ID) REFERENCES PROMO (ID) ON
    DELETE
        CASCADE
    );