DROP TABLE USER;

CREATE TABLE
    USER
    (
        SHAKLEE_ID VARCHAR(20) NOT NULL,
        CONTACT_ID VARCHAR(20) NOT NULL,
        FIRST_NAME VARCHAR(4000),
        LAST_NAME VARCHAR(4000),
        EMAIL VARCHAR(128),
        CREATED DATETIME NOT NULL,
        UPLINE_SHAKLEE_ID VARCHAR(20) NOT NULL,
        SPONSOR_SHAKLEE_ID VARCHAR(20) NOT NULL,
        PRIMARY KEY (CONTACT_ID)
    );
    
-- upload data from SALES FORCE